### ISSUE TITLE
Data integrity check

### ISSUE THREAD

**Issue by kieranhogg** [CranleighAD/isams-tools#16]
New feature: poll the database for data oddities:
- duplicate set entries
- duplicate reports

etc

**Comment by kieranhogg** [comment]
@johncarney82 can you add your SQL scripts?

**Comment by johncarney82** [comment]
We should agree on the scripts we want, what columns we need and whether they are actually giving expected results.

**Comment by johncarney82** [comment]
Attached.
[Duplicates.txt](https://github.com/CranleighAD/isams-tools/files/535748/Duplicates.txt)

**Comment by kieranhogg** [comment]
Does query 2 take into account shared groups?

**Comment by johncarney82** [comment]
It does now, yes. Comment needs updating / removing.

**Comment by kieranhogg** [comment]
Need a hand with: 
    AND S1.txtSetCode NOT LIKE '%PE%'
    AND S1.txtSetCode NOT LIKE '%PR%'

Ideally, we want: AND S1.txtSetCode NOT LIKE IN (...) then ... can be a setting but that's not valid SQL. Any ideas?

**Comment by kieranhogg** [comment]
Also it still seems to be flagging shared groups

**Comment by johncarney82** [comment]
If you want to use NOT IN (...) it would have an extra join onto the Subject table. I just used set codes because it meant writing the query was easier/faster. Instead we would have:

Sub1.txtName NOT IN ('Physical Education','Private Reading','Some other subject')

Show me the shared group thing tomorrow.

**Comment by johncarney82** [comment]
Updated version attached.
[Duplicates.txt](https://github.com/CranleighAD/isams-tools/files/537948/Duplicates.txt)

**Comment by kieranhogg** [comment]
Changed the teacher query to ignore the subjects:

```
SELECT
    Sets.txtSetCode
    ,Sets.txtTeacher
    ,TTS.txtTeacher
    ,S1.Fullname AS [Set Teacher]
    ,S2.Fullname AS [Timetable Teacher]
    ,Sub.txtSubjectName
FROM
    TblTeachingManagerSets Sets
    INNER JOIN TblStaff S1
        ON S1.User_Code=Sets.txtTeacher
    INNER JOIN TblTimetableManagerSchedule TTS
        ON TTS.txtCode=Sets.txtSetCode
    INNER JOIN TblStaff S2
        ON S2.User_Code=TTS.txtTeacher
    LEFT JOIN TblTeachingManagerSubjects Sub
        ON Sub.TblTeachingManagerSubjectsID=Sets.intSubject
WHERE
    Sets.txtTeacher NOT IN (
        SELECT txtTeacher FROM TblTimetableManagerSchedule
        WHERE txtCode = Sets.txtSetCode
    )
AND Sub.txtSubjectName NOT IN %s`
```
